---
title: "Anexo C"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Para estimar los coeficientes de AIC y BIC del portafolio bajo los modelos heterocedásticos propuestos se lleva a cabo lo siguiente:


Para el ARMA - GARCH(1,1)
```{r}
  
  library(fGarch)
x<-read.csv('C:/Users/Martin/Downloads/Var.csv',header=TRUE,sep=","); #Precios del portafolio, es necesario actualizar la ruta para que tome el archivo de Var.csv
xx<-diff(log(x$Valor))
fitgxx1 = garchFit(formula  =  ~  garch(1, 1), data = xx, trace = FALSE)  #Se ajusta GARCH11 del portafolio
summary(fitgxx1)
```

Para el ARMA - EGARCH(1,1)
```{r}
library(rugarch)
x<-read.csv('C:/Users/Martin/Downloads/Var.csv',header=TRUE,sep=","); #Precios del portafolio, es necesario actualizar la ruta para que tome el archivo de Var.csv
xx<-diff(log(x$Valor))
egarchx1<-ugarchspec(variance.model = list(model = "eGARCH", garchOrder = c(1,1)),
                     mean.model = list(armaOrder = c(0,0)))
egarch11fitxx1<-ugarchfit(egarchx1, xx,solver = 'hybrid')
egarch11fitxx1
```

Para el ARMA - TGARCH(1,2)
```{r}
library(fGarch)
x<-read.csv('C:/Users/Martin/Downloads/Var.csv',header=TRUE,sep=","); #Precios del portafolio, es necesario actualizar la ruta para que tome el archivo de Var.csv
xx<-diff(log(x$Valor))
fitgxx1 <- garchFit( formula = ~aparch(1,2), xx, delta = 1, include.delta = FALSE)  #Se ajusta TGARCH21 del portafolio
summary(fitgxx1)

```
